// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    return robot.hear(/^todo (.*)/i, function(msg) {
      var Trello, t, title;
      title = "" + msg.match[1];
      Trello = require("node-trello");
      t = new Trello(process.env.HUBOT_TRELLO_KEY, process.env.HUBOT_TRELLO_TOKEN);
      return t.post("/1/cards", {
        name: title,
        idList: process.env.HUBOT_TRELLO_LIST
      }, function(err, data) {
        if (err) {
          msg.send("ERROR");
        }
        return msg.send("「" + title + "」 をTrelloに保存しました");
      });
    });
  };

}).call(this);
